package com.dm.sharedmoduleapp.smmodel.vo.client;

import com.dm.sharedmoduleapp.smmodel.vo.common.UsersView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 21 21:37:33 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersViewClient extends ViewUsageImpl implements UsersView {
    /**
     * This is the default constructor (do not remove).
     */
    public UsersViewClient() {
    }

    public void refresh() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refresh",null,null);
        return;
    }
}
