package com.dm.menudemoapp.mdmodel.demo.view;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ProgrammaticViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 26 10:50:05 EST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClaimsMasterViewRowImpl extends ProgrammaticViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ClaimsMasterViewRowImpl() {
    }
}
