package com.dm.menudemoapp.mdmodel.demo.view;

import java.util.ArrayList;
import java.util.Collection;

import java.util.HashMap;
import java.util.Map;

import oracle.jbo.DataFilter;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 26 10:33:46 EST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CreditCardsViewImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CreditCardsViewImpl() {
    }

    private Map dataRow(Integer id, String type, String value) {

        Map ret = new HashMap();
        ret.put("Id", id);
        ret.put("Type", type);
        ret.put("Value", value);
        return ret;

    }

    private Collection<Object> getData(DataFilter filter) {

        Collection<Object> rows = new ArrayList<Object>();

        rows.add(dataRow(1, "Select", null));
        rows.add(dataRow(2, "Master Card", "MC"));
        rows.add(dataRow(3, "Visa Card", "VC"));
        rows.add(dataRow(4, "Amex Card", "AC"));


        return rows;

    }


    @Override
    protected Collection<Object> getScrollableData(ScrollableDataFilter scrollableDataFilter) {
        //        return super.getScrollableData(scrollableDataFilter);
        return getData(scrollableDataFilter);
    }

    @Override
    protected Collection<Object> getRangePagingData(RangePagingDataFilter rangePagingDataFilter) {
        //        return super.getRangePagingData(rangePagingDataFilter);
        return getData(rangePagingDataFilter);
    }
}
