package com.dm.sharedmoduleapp.smmodel.vo;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ProgrammaticViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 01 11:09:18 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersViewRowImpl extends ProgrammaticViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public UsersViewRowImpl() {
    }
}
