package com.dm.sharedmoduleapp.smmodel.vo;


import com.dm.sharedmoduleapp.smmodel.vo.common.UsersView;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 01 11:09:19 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersViewImpl extends ProgrammaticViewObjectImpl implements UsersView {
    /**
     * This is the default constructor (do not remove).
     */
    public UsersViewImpl() {
    }

    ADFLogger logger = ADFLogger.createADFLogger(UsersViewImpl.class);

    private List<Object> populateData() {

        List<Object> rows = new ArrayList<Object>();

        HashMap<String, Object> row1 = new HashMap<String, Object>();
        row1.put("PersonId", "1");
        row1.put("FirstName", "Dinil");
        row1.put("LastName", "Mithra");
        rows.add(row1);

        HashMap<String, Object> row2 = new HashMap<String, Object>();
        row2.put("PersonId", "2");
        row2.put("FirstName", "Aparna");
        row2.put("LastName", "Krishna");
        rows.add(row2);

        HashMap<String, Object> row3 = new HashMap<String, Object>();
        row3.put("PersonId", "3");
        row3.put("FirstName", "Don");
        row3.put("LastName", "King");
        rows.add(row3);

        HashMap<String, Object> row4 = new HashMap<String, Object>();
        row4.put("PersonId", "4");
        row4.put("FirstName", "Scott");
        row4.put("LastName", "Man");
        rows.add(row4);

        HashMap<String, Object> row5 = new HashMap<String, Object>();
        row5.put("PersonId", "5");
        row5.put("FirstName", "Joby");
        row5.put("LastName", "Joseph");
        rows.add(row5);

        int counter = 1;
        if (logger.isInfo()) {

            if (rows != null) {

                for (Object obj : rows) {

                    HashMap<Object, Object> row = (HashMap<Object, Object>)obj;

                    if (row != null) {
                        logger.info("\n");
                        logger.info("Row " + (counter++) + ":");
                        for (Map.Entry<Object, Object> entry : row.entrySet())
                            logger.info("Key = " + entry.getKey() +
                                        ", Value = " + entry.getValue());
                    }


                }
            }

        }
        return rows;

    }


    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {

        ArrayList<Object> rows = (ArrayList<Object>)populateData();
        return rows;
    }

    public void refresh() {
        this.forceExecuteQueryOfSharedVO();
    }


}
