package com.dm.sharedmoduleapp.smmodel.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 21 21:37:33 EDT 2020
// ---------------------------------------------------------------------
public interface UsersView extends ViewObject {
    void refresh();
}
