package com.dm.pgmapp.pgmmodel.views;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 23:19:27 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }





    private Collection<Object> populateData() {

        Collection<Object> rows = new ArrayList<Object>();

        HashMap<String, Object> row1 = new HashMap<String, Object>();
        row1.put("Id", 90);
        row1.put("Name", "Executive");
        rows.add(row1);

        HashMap<String, Object> row2 = new HashMap<String, Object>();
        row2.put("Id", 60);
        row2.put("Name", "IT");
        rows.add(row2);

        HashMap<String, Object> row3 = new HashMap<String, Object>();
        row3.put("Id", 100);
        row3.put("Name", "Finance");
        rows.add(row3);

        HashMap<String, Object> row4 = new HashMap<String, Object>();
        row4.put("Id", 30);
        row4.put("Name", "Purchasing");
        rows.add(row4);


        //        50      Shipping
        //        80      Sales
        //        10      Administration
        //        20      Marketing
        //        40      Human Resources
        //        70      Public Relations
        //        110     Accounting


        return rows;


    }


    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {
        //        Collection<Object> value = super.getScrollableData(filter);
        Collection<Object> value = (ArrayList<Object>) populateData();
        return value;
    }

}

