package com.dm.pgmapp.pgmmodel.views;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 19 23:28:59 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }
    private Collection<Object> populateData() {

        Collection<Object> rows = new ArrayList<Object>();

        HashMap<String, Object> row1 = new HashMap<String, Object>();
        row1.put("Id", 1);
        row1.put("FirstName", "Steven");
        row1.put("LastName", "King");
        row1.put("DepartmentId", 100);
        rows.add(row1);

        HashMap<String, Object> row2 = new HashMap<String, Object>();
        row2.put("Id", 2);
        row2.put("FirstName", "Neena");
        row2.put("LastName", "Kochhar");
        row2.put("DepartmentId", 100);
        rows.add(row2);

        HashMap<String, Object> row3 = new HashMap<String, Object>();
        row3.put("Id", 3);
        row3.put("FirstName", "Lex");
        row3.put("LastName", "De Haan");
        row3.put("DepartmentId", 100);
        rows.add(row3);


        HashMap<String, Object> row4 = new HashMap<String, Object>();
        row4.put("Id", 4);
        row4.put("FirstName", "Alexander");
        row4.put("LastName", "Hunold");
        row4.put("DepartmentId", 90);
        rows.add(row4);

        HashMap<String, Object> row5 = new HashMap<String, Object>();
        row5.put("Id", 5);
        row5.put("FirstName", "Bruce");
        row5.put("LastName", "Ernst");
        row5.put("DepartmentId", 90);
        rows.add(row5);

        HashMap<String, Object> row6 = new HashMap<String, Object>();
        row6.put("Id", 6);
        row6.put("FirstName", "David");
        row6.put("LastName", "Austin");
        row6.put("DepartmentId", 60);
        rows.add(row6);

        return rows;
    }


    /**
     * getRangePagingData - for custom java data source support.
     */
    public Collection<Object> getRangePagingData(RangePagingDataFilter filter) {
        Collection<Object> value = super.getRangePagingData(filter);
        return value;
    }

    /**
     * retrieveDataByKey - for custom java data source support.
     */
    public Collection<Object> retrieveDataByKey(Key key, int size) {
        Collection<Object> value = super.retrieveDataByKey(key, size);
        return value;
    }

    /**
     * getScrollableData - for custom java data source support.
     */
    public Collection<Object> getScrollableData(ScrollableDataFilter filter) {
        //        Collection<Object> value = super.getScrollableData(filter);
        Collection<Object> value = populateData();
        return value;
    }
}

