package com.dm.adf.hrapp.hrmodel.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 21 21:06:04 EST 2020
// ---------------------------------------------------------------------
public interface HRService extends ApplicationModule {
    String sayHai();
}

