package com.dm.pgmapp.pgmmodel.entity;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.ProgrammaticEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 12:16:17 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentImpl extends ProgrammaticEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id {
            protected Object get(DepartmentImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DepartmentImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Name {
            protected Object get(DepartmentImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DepartmentImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Employee {
            protected Object get(DepartmentImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(DepartmentImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;


        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }

        protected abstract Object get(DepartmentImpl object);

        protected abstract void put(DepartmentImpl object, Object value);
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int EMPLOYEE = AttributesEnum.Employee.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.dm.pgmapp.pgmmodel.entity.Department");
    }


}

