package com.dm.pgmapp.pgmmodel.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 12:18:46 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentCollImpl() {
    }
}

