package com.dm.pgmapp.pgmmodel.entity;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.ProgrammaticEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 12:18:06 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeImpl extends ProgrammaticEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id {
            protected Object get(EmployeeImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EmployeeImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FirstName {
            protected Object get(EmployeeImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EmployeeImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LastName {
            protected Object get(EmployeeImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EmployeeImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DepartmentId {
            protected Object get(EmployeeImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EmployeeImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Department {
            protected Object get(EmployeeImpl obj) {
                return obj.getAttributeInternal(index());
            }

            protected void put(EmployeeImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected abstract Object get(EmployeeImpl object);

        protected abstract void put(EmployeeImpl object, Object value);

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.dm.pgmapp.pgmmodel.entity.Employee");
    }
}

