package com.dm.pgmapp.pgmmodel.entity;

import oracle.jbo.server.ProgrammaticEntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 20 12:18:06 EDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeDefImpl extends ProgrammaticEntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeDefImpl() {
    }
}

