package com.dm.pgmapp.pgmmodel.views;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;

import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 25 22:20:05 EST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }

    @Override
    protected Collection<Object> getScrollableData(ScrollableDataFilter scrollableDataFilter) {
        //        return super.getScrollableData(scrollableDataFilter);

        Collection<Object> rows = populateDepartments();
        return rows;
    }

    private Collection<Object> populateDepartments() {

        Collection<Object> rows = new ArrayList<Object>();

        HashMap map = new HashMap();
        map.put("Id", 90);
        map.put("Name", "Executive");
        rows.add(map);

        map = new HashMap();
        map.put("Id", 60);
        map.put("Name", "IT");
        rows.add(map);

        map = new HashMap();
        map.put("Id", 100);
        map.put("Name", "Finance");
        rows.add(map);

        map = new HashMap();
        map.put("Id", 30);
        map.put("Name", "Purchasing");
        rows.add(map);


        //        50      Shipping
        //        80      Sales
        //        10      Administration
        //        20      Marketing
        //        40      Human Resources
        //        70      Public Relations
        //        110     Accounting


        return rows;


    }
}
