package com.dm.pgmapp.pgmmodel.views;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ProgrammaticViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 25 22:20:05 EST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewRowImpl extends ProgrammaticViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewRowImpl() {
    }

    /**
     * Gets Department entity object.
     * @return the Department
     */
    public EntityImpl getDepartment() {
        return (EntityImpl)getEntity(0);
    }
}
