package com.dm.pgmapp.pgmmodel.views;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import oracle.jbo.RowContext;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 25 22:20:55 EST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ProgrammaticViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }


    @Override
    protected Collection<Object> getScrollableData(ScrollableDataFilter scrollableDataFilter) {
      
        RowContext ctx = scrollableDataFilter.getRowContext();
        
        String masterAccessorName = ctx.getMasterAccessorName();
        Map masterRowData = (Map)ctx.getMasterRowDataProvider();

        Collection<Object> rows =
            populateEmployees(scrollableDataFilter, masterAccessorName,
                              masterRowData);
        return rows;  //        return super.getScrollableData(scrollableDataFilter);
        
    }

    private Collection<Object> populateEmployees(ScrollableDataFilter scrollableDataFilter,
                                                 String masterAccessorName,
                                                 Map masterRowData) {

        Collection<Object> rows = new ArrayList<Object>();

        HashMap map = new HashMap();

        map = new HashMap();
        map.put("Id", 1);
        map.put("FirstName", "Steven");
        map.put("LastName", "King");
        map.put("DepartmentId", 100);
        rows.add(map);

        map = new HashMap();
        map.put("Id", 2);
        map.put("FirstName", "Neena");
        map.put("LastName", "Kochhar");
        map.put("DepartmentId", 100);
        rows.add(map);

        map = new HashMap();
        map.put("Id", 3);
        map.put("FirstName", "Lex");
        map.put("LastName", "De Haan");
        map.put("DepartmentId", 100);
        rows.add(map);


        map = new HashMap();
        map.put("Id", 4);
        map.put("FirstName", "Alexander");
        map.put("LastName", "Hunold");
        map.put("DepartmentId", 90);
        rows.add(map);

        map = new HashMap();
        map.put("Id", 5);
        map.put("FirstName", "Bruce");
        map.put("LastName", "Ernst");
        map.put("DepartmentId", 90);
        rows.add(map);

        map = new HashMap();
        map.put("Id", 6);
        map.put("FirstName", "David");
        map.put("LastName", "Austin");
        map.put("DepartmentId", 60);
        rows.add(map);

        return rows;
    }

}
